# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1c89af8ef7f1aa11e3cedd8b6fb1c72cf5a22731ef95752bcb8179c18e2016e0af101f73886bca6168bd7b0fa1f288c32b682ed9b962043c57a6cc26894183b9

test:
  secret_key_base: 0831c2efc6d9af5fa6d6c0a7b16438243d7d58f8de7c4ef70c1f54fad47ff881bf9a3a9c02e22b404a19943082baf2c631df4f0b2bdd7a4746033f6cfd4bf3a7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
